### ISSUE TITLE
startup failure

### ISSUE THREAD

**Issue by tier940** [bruberu/GregTechFoodOption#13]
https://pastebin.com/AAhjKncS

GregTech CE: Unofficial
> gregtech-1.12.2-2.1.0-beta.jar

GregTech Food Option
> GregTech Food Option-1.12.2-1.1.0.jar

**Comment by htmlcsjs** [comment]
Are you using a modpack?
Looks like the ceu coremod for fluid tooltips failed to inject

**Comment by tier940** [comment]
@htmlcsjs 
Yes, I am using Modpack.
We will gather some more information and get back to you.

**Comment by tier940** [comment]
I tried emptying the scripts of crafttweaker and initializing the cfg, but it still never started.
It seems that the update of GregTech CE: Unofficial is preventing it from starting.

**Comment by bruberu** [comment]
Fixed in 1.1.1. Thanks for reporting!
