### ISSUE TITLE
GTFO will cause JEI  pages of industrialforegoing disappear

### ISSUE THREAD

**Issue by magcicada** [bruberu/GregTechFoodOption#15]
Mod will cause the JEI pages of `Industrial Foregoing` disappear, I can't find the JEI pages but recipes work well.
Mod list:
`CodeChickenLib-1.12.2-3.2.3.358-universal`
`Forgelin-1.8.4`
`GregTech Food Option-1.12.2-1.2.0`
`gregtech-1.12.2-2.1.1-beta`
`industrialforegoing-1.12.2-1.12.13-237`
`jei_1.12.2-4.16.1.302`
`tesla-core-lib-1.12.2-1.0.18`
and this is the log: [latest.log](https://github.com/bruberu/GregTechFoodOption/files/8049160/latest.log)

**Comment by bruberu** [comment]
Does removing GTFO fix the issue?

**Comment by magcicada** [comment]
yes, when removing gtfo it works well.

**Comment by bruberu** [comment]
Should be fixed in 1.2.1. Thanks for reporting!
