### ISSUE TITLE
[1.12.2] Crash upon Startup (java.lang.NoClassDefFoundError: nc.recipe.BasicRecipeHandler)

### ISSUE THREAD

**Issue by aking4125** [bruberu/GregTechFoodOption#2]
Hello, we recently found this add-on to Gregtech and wanted to try it, however it crashes the modpack upon startup. Any ideas?

[crash-2021-05-10_08.37.52-client.txt](https://github.com/bruberu/GregTechFoodOption/files/6452093/crash-2021-05-10_08.37.52-client.txt)

**Comment by bruberu** [comment]
Ok, fixed with a few other things in 0.5.2! Thank you, again!
