### ISSUE TITLE
Crash with NC:O

### ISSUE THREAD

**Issue by whatsapp2** [bruberu/GregTechFoodOption#20]
Having a couple issues when loading a little test modpack only with 5 mods:

1. CodeChickenLib-1.12.2-3.2.3.358-universal
2. gregtech-1.12.2-2.1.4-beta
3. GregTech+Food+Option-1.12.2-1.4.1
4. NuclearCraft-2o.5.5-1.12.2
5. QMD-1.1-beta5-1.12.2

When I take out GTFO game doesn't crash

**Comment by bruberu** [comment]
May I see the error log?

**Comment by whatsapp2** [comment]
Sure, here it is
[crash-2022-03-05_14.52.33-client.txt](https://github.com/bruberu/GregTechFoodOption/files/8191456/crash-2022-03-05_14.52.33-client.txt)

**Comment by bruberu** [comment]
Fixed in 1.4.2. Thank you for bringing this to my attention!
