### ISSUE TITLE
Can Roast Potato on a Stick  be made stackable? 

### ISSUE THREAD

**Issue by MrKono** [bruberu/GregTechFoodOption#21]
Can "Roast Potato on a Stick"  be made stackable because "Chum on a Stick" can be made stacked.

**Comment by bruberu** [comment]
After thinking about it a little, what if it was made such that both skewer items could be stacked to 16? This does make it slightly less annoying, but also makes it less likely that people would use these throughout a playthrough (as that is not intended).

**Comment by MrKono** [comment]
I see. Thank you for your support.

**Comment by bruberu** [comment]
I just changed the code to make it happen; a new release should come out right after the next CEu version (to fix an upcoming incompatibility).
