### ISSUE TITLE
GTFO crashed my sever

### ISSUE THREAD

**Issue by yuyijun12** [bruberu/GregTechFoodOption#28]
here is the crash report
[crash-2022-08-04_19.13.20-server.txt](https://github.com/bruberu/GregTechFoodOption/files/9259183/crash-2022-08-04_19.13.20-server.txt)

**Comment by bruberu** [comment]
Did the crash appear just on startup?

**Comment by bruberu** [comment]
Ok, I don't seem to be able to replicate this bug with just GTFO, without any other mods. Can you send your whole server instance?

**Comment by yuyijun12** [comment]
ok

**Comment by bruberu** [comment]
While you're working on that, one possible fix may be to update your version of GTFO, since I believe a similar glitch appeared in the first public version of GTFO 1.6.3, which was available for a few hours. So, you should try redownloading 1.6.3 to see if that resolves it.

**Comment by yuyijun12** [comment]
I can't send a compressed package directly。
So there is a mega cloud
[https://mega.nz/file/IsMXkK7A#6RbqwFfgR4sCiLucaLE4mYqcOsyP6ddy7D7cxfg9h3w](url)

**Comment by bruberu** [comment]
What did you use to launch this instance?

**Comment by bruberu** [comment]
It appears that you didn't send all the mods that you had, could you send those as well?

**Comment by bruberu** [comment]
![image](https://user-images.githubusercontent.com/80226372/182907287-43a67e17-5eef-47c2-8c55-4f5f1f43cc0d.png)
Using these mods, I cannot replicate your issue.

**Comment by yuyijun12** [comment]
That's strange my server dont crash again, but why?

**Comment by bruberu** [comment]
Did you redownload GTFO? If so, you downloaded a slightly newer version that had the fix.

**Comment by bruberu** [comment]
Also, I manually downloaded the rest of your mods, and I still cannot replicate the crash, which means that it is likely your GTFO version was too low.

**Comment by yuyijun12** [comment]
possibly yes

**Comment by bruberu** [comment]
OK, I'll just mark this issue as resolved if it's all fine now.

**Comment by yuyijun12** [comment]
thanks
