### ISSUE TITLE
Lemon trees drop oranges instead of lemons

### ISSUE THREAD

**Issue by Discusser** [bruberu/GregTechFoodOption#36]
can be fixed by changing this line
https://github.com/bruberu/GregTechFoodOption/blob/c0f1e4c1daa33b70afe5fc21c6b8cda120c4624f/src/main/java/gregtechfoodoption/worldgen/trees/LemonTree.java#L59
(also how do i submit pull requests)

edit: lime trees also seem to drop oranges

**Comment by bruberu** [comment]
Was fixed by https://github.com/bruberu/GregTechFoodOption/commit/960907956632bca7c3a5a9c8f136a2ac43b4e8ca
