### ISSUE TITLE
Greenhouse issue

### ISSUE THREAD

**Issue by BlazeHunterVN1610** [bruberu/GregTechFoodOption#42]
Whenever the greenhouse multiblock formed, it always has this problem:
![2022-11-29_09 06 44](https://user-images.githubusercontent.com/111768452/204421107-fef7db65-bc07-48c9-966e-11efbb0ec03c.png)
even though there's no block on the roof
![2022-11-29_09 14 59](https://user-images.githubusercontent.com/111768452/204422188-d5841b3b-f195-4193-8b3b-ac3af8ff1f0b.png)

I test this in both survival and creative world

**Mod version:** 
gregtech-1.12.2-2.4.4-beta
GregTech+Food+Option-1.12.2-1.8.2

(I'm not good at English, sorry)

**Comment by bruberu** [comment]
Try running a recipe in it; does that fix the issue?

**Comment by BlazeHunterVN1610** [comment]
It's still running, but it's take much longer to run

**Comment by bruberu** [comment]
It appears you may have some extra frames on the top of the multiblock; perhaps removing those would fix it.

**Comment by bruberu** [comment]
Actually, it seems fine; could you send me your world's files?

**Comment by BlazeHunterVN1610** [comment]
So, there's a few problem:
First, when I build the multiblock, the problem appears, even though there is no block on top of it . If I run a recipe, the problem disappeared
Second, the problem will appear if the time is night or the weather is rain
Third, TheOneProbe always display same progress bar, whether the multiblock has problem or not

Also, this is my test world:
[Gregtech Test World.zip](https://github.com/bruberu/GregTechFoodOption/files/10110074/Gregtech.Test.World.zip)

Full mod list:
!mixinbooter-4.2
_bansoukou-4.3.1
CodeChickenLib-1.12.2-3.2.3.358-universal
GregTech+Food+Option-1.12.2-1.8.2
gregtech-1.12.2-2.4.4-beta
GregicalityMultiblocks-1.12.2-1.1.5
HadEnoughItems_1.12.2-4.23.0
loliasm-5.6
topaddons-1.12.2-1.13.0
theoneprobe-1.12-1.4.28

**Comment by bruberu** [comment]
I am still unable to replicate the issue when it is daytime and not raining. I will modify its tooltip to make it clearer that it runs more slowly at night, and make it run as it rains.

**Comment by BlazeHunterVN1610** [comment]
I found out that TheOneProbe and GT scanner have the same progress displaying bug
For example, I build a greenhouse multiblock with 1 iv energy hatch and run this recipe:
![2022-11-29_22 07 19](https://user-images.githubusercontent.com/111768452/204566075-ab81a382-851e-49a9-a6f2-d422d7c1781c.png)
When I run the recipe without the warning, it takes 12.25 seconds to run the recipe, TOP and GT scanner also show that too
![2022-11-29_22 17 57](https://user-images.githubusercontent.com/111768452/204569310-d9b651e8-84a3-4470-b297-8d9ab5360a60.png)
If the warning appears, it takes 25 seconds to run the recipe, but TOP and GT scanner still showing 12 seconds
![2022-11-29_22 19 18](https://user-images.githubusercontent.com/111768452/204571575-09fb8075-af43-428d-8070-5a36d3ca7f62.png)

**Comment by MrKono** [comment]
I am sorry to interrupt you.
The TOP's display time does not change, but I feel like the speed of the progress bar seems to have increased by 0.5 times.

**Comment by bruberu** [comment]
Although the greenhouse is supposed to run twice as slowly without adequate sunlight, I should probably try to get it to show this.
