### ISSUE TITLE
Crash with laster GTCEu (is not 2.5.4)

### ISSUE THREAD

**Issue by Darknight123MC** [bruberu/GregTechFoodOption#44]
``A mixin class in GTFO is crash with CEu (2.5.5?).
It is in recipe/mixins/RecipeMapFluidCannerMixin.
You use the checkLacingRecipes method to rewrite the findRecipe.
But the method
```java
checkLacingRecipes(long voltage, List<ItemStack> inputs, List<FluidStack> fluidInputs, int outputFluidTankCapacity, boolean exactVoltage, CallbackInfoReturnable<Recipe> cir, Recipe recipe, Iterator var8, ItemStack input, ItemStack inputStack, ItemStack fluidHandlerItemStack, IFluidHandlerItem fluidHandlerItem)
```
is a error method.
The parameters of checkLacingRecipes is old.
New parameters:
`findRecipe(long voltage, List<ItemStack> inputs, List<FluidStack> fluidInputs, boolean exactVoltage)`

Crash Report:
[here](https://pastebin.mozilla.org/1tRni41T)

**Comment by bruberu** [comment]
It appears that you're using an unreleased version of CEu that I haven't prepared GTFO for currently. You can downgrade CEu to the latest released version for now (although hopefully that doesn't have any major glitches on it).

**Comment by Darknight123MC** [comment]
This is a good idea, but I think you'll need to be compatible with it at some point in the future.

**Comment by Darknight123MC** [comment]
Recently CEu has been rewriting and modifying the code more and more, maybe the author needs to wait until a more stable stage?

**Comment by Darknight123MC** [comment]
Just now, I wrote a fix myself, maybe you can open a new branche to receive him.
