### ISSUE TITLE
EBO processing time is multiplied by the number of parallel processes

### ISSUE THREAD

**Issue by sjcl** [bruberu/GregTechFoodOption#50]
For example, a recipe that takes 5 seconds would take 10 seconds if you process 2 in parallel.
https://github.com/bruberu/GregTechFoodOption/blob/40d5b9adde7afa26728f1a4eb29ec5ea146ad0ec/src/main/java/gregtechfoodoption/machines/multiblock/MetaTileEntityElectricBakingOven.java#L379

**Comment by bruberu** [comment]
Thanks! Should be fixed in the next update. I just changed this line back to ParallelLogicType.MULTIPLY, now that it no longer crashes.

**Comment by bruberu** [comment]
Yes, it used to do that as the logic used to divide by the EU/t, which is zero for EBO recipes. I think I fixed that a while ago, but I forgot to change this here.

**Comment by sjcl** [comment]
That makes sense. Now I can get on with compressing the crackers.
Thanks again!
