### ISSUE TITLE
Recipe duplicates/conflicts with base GT

### ISSUE THREAD

**Issue by xeals** [bruberu/GregTechFoodOption#53]
Playing GregTech Community Pack which is more or less vanilla as far as GT goes, added GTFO, and have found a few places where GTFO adds recipes but doesn't disable or a config to disable default recipes.

Most recipes are only distinguished by the presence of an additional input (rather than a circuit) which it seems GT has moved away from, especially with the addition of the dedicated circuit slot.

Non-exhaustive list (including those found below):

- Default salt electrolysis (no circuit) and GTFO's salt electrolysis (circuit 1)
- Default HCl elecrolysis (no gold) and GTFO's chloroauric acid (gold)
- Default water electrolysis (no circuit) and GTFO's water electrolysis (circuit 1)
- GTFO's creosote distillation is a different voltage/duration and produces additional outputs with no way to deconflict them at all

GregTech 2.7.2  
GregTech Food Option 1.9.3.1

<details>
<summary>
Output of `/gt recipecheck`
</summary>
<pre>
[14:07:46] [Server thread/INFO] [GregTech]: [Recipe Checker] Completed recipe check!
[14:07:46] [Server thread/INFO] [GregTech]: [Recipe Checker] Found 5 potential conflicts
[14:07:46] [Server thread/ERROR] [GregTech]: 
[In Recipe map] :"mixer"
[14:07:46] [Server thread/ERROR] [GregTech]: 
[Tried matching]: EU/t: 120, Duration: 260
Item inputs:
     {  minecraft:sugar * 1 (Meta 0) } * 1
     {  Config circuit #1 } * 1
Fluid inputs:
    fluid.tile.water * 5000
    gregtech.material.gtfo_cane_syrup * 5000
Fluid outputs:
    gregtech.material.gtfo_sweetened_diluted_cane_syrup_mixture * 10000
[Also Found]: EU/t: 80, Duration: 260
Item inputs:
    (OreDict: "dustSugar") {  minecraft:sugar * 24 (Meta 0) } * 24
Fluid inputs:
    fluid.tile.water * 2000
Fluid outputs:
    gregtech.material.gtfo_unheated_cane_syrup * 2000
[14:07:46] [Server thread/ERROR] [GregTech]: 
[In Recipe map] :"electrolyzer"
[14:07:46] [Server thread/ERROR] [GregTech]: 
[Tried matching]: EU/t: 30, Duration: 56
Item inputs:
    (OreDict: "dustSalt") {  (MetaItem) dustSalt * 2 } * 2
     {  Config circuit #1 } * 1
Item outputs:
    (MetaItem) dustSodium * 1
Fluid outputs:
    gregtech.material.chlorine * 1000
[Also Found]: EU/t: 30, Duration: 56
Item inputs:
    (OreDict: "dustSalt") {  (MetaItem) dustSalt * 2 } * 2
Item outputs:
    (MetaItem) dustSodium * 1
Fluid outputs:
    gregtech.material.chlorine * 1000
[14:07:46] [Server thread/ERROR] [GregTech]: 
[Tried matching]: EU/t: 480, Duration: 300
Item inputs:
    (OreDict: "dustGold") {  (MetaItem) dustGold * 2 } * 2
Fluid inputs:
    gregtech.material.hydrochloric_acid * 8000
Fluid outputs:
    gregtech.material.gtfo_chloroauric_acid * 2000
    gregtech.material.hydrogen * 3000
[Also Found]: EU/t: 30, Duration: 36
Fluid inputs:
    gregtech.material.hydrochloric_acid * 1000
Fluid outputs:
    gregtech.material.hydrogen * 1000
    gregtech.material.chlorine * 1000
[14:07:46] [Server thread/ERROR] [GregTech]: 
[Tried matching]: EU/t: 120, Duration: 400
Item inputs:
    (OreDict: "dustSalt") {  (MetaItem) dustSalt * 2 } * 2
     {  Config circuit #2 } * 1
Fluid inputs:
    fluid.tile.water * 3000
Item outputs:
    (MetaItem) sodium_chlorate_dust * 5
Fluid outputs:
    gregtech.material.hydrogen * 6000
[Also Found]: EU/t: 30, Duration: 56
Item inputs:
    (OreDict: "dustSalt") {  (MetaItem) dustSalt * 2 } * 2
Item outputs:
    (MetaItem) dustSodium * 1
Fluid outputs:
    gregtech.material.chlorine * 1000
[14:07:46] [Server thread/ERROR] [GregTech]: 
[In Recipe map] :"forming_press"
[14:07:46] [Server thread/ERROR] [GregTech]: 
[Tried matching]: EU/t: 30, Duration: 20
Item inputs:
     {  (MetaItem) component.caplet_body * 1 } * 1
    (OreDict: "dustSmallPlutonium241") {  (MetaItem) dustSmallPlutonium241 * 1 } * 1
     {  (MetaItem) component.caplet_cap * 1 } * 1
Item outputs:
    (MetaItem) food.plutonium_241_caplet * 1
[Also Found]: EU/t: 120, Duration: 100
Item inputs:
     {  (MetaItem) component.caplet_body * 4 } * 4
     {  (MetaItem) component.caplet_cap * 4 } * 4
Item outputs:
    (MetaItem) food.gel_caplet * 4
</pre>
</details>

**Comment by bruberu** [comment]
I have already fixed a lot of these recipe conflicts in unreleased versions of GTFO, mainly by moving recipes like chloroauric acid and sodium chlorate to chemical reactors to prevent conflicts. In fact, the original creosote and salt recipes are removed, but they aren't removed from JEI due to a GTCEu bug being fixed in 2.7.3. I've made some minor tweaks removing circuits from some recipes and changing the creosote distillation recipe to have the duration and EU/t of the original.
