### ISSUE TITLE
Server crashing bug with sprinkler and cocoa beans

### ISSUE THREAD

**Issue by KatatsumuriPan** [bruberu/GregTechFoodOption#54]
Servers crash when cocoa beans grow beyond their limit due to sprinklers.

**Comment by bruberu** [comment]
What is the crash log?

**Comment by bruberu** [comment]
OK, I've actually replicated this issue on singleplayer; I'll fix this now.

**Comment by bruberu** [comment]
Fixed with [this commit](https://github.com/bruberu/GregTechFoodOption/commit/648fc573241827712d5d51818293fde60c08b2db)
