### ISSUE TITLE
Crash On World Startup 

### ISSUE THREAD

**Issue by caniplzjustlogin4godsakesthistakesforev** [bruberu/GregTechFoodOption#62]
[crash-2023-11-16_10.34.50-server.txt](https://github.com/bruberu/GregTechFoodOption/files/13381134/crash-2023-11-16_10.34.50-server.txt)
[latest.log](https://github.com/bruberu/GregTechFoodOption/files/13381136/latest.log)

**Comment by bruberu** [comment]
[gregtechfoodoption-1.10.1-beta.zip](https://github.com/bruberu/GregTechFoodOption/files/13385350/gregtechfoodoption-1.10.1-beta.zip)
Can you check if using this version instead fixes your issue?

**Comment by caniplzjustlogin4godsakesthistakesforev** [comment]
> [gregtechfoodoption-1.10.1-beta.zip](https://github.com/bruberu/GregTechFoodOption/files/13385350/gregtechfoodoption-1.10.1-beta.zip) Can you check if using this version instead fixes your issue?

I think it did, or at least i'm not getting that crash when opening the world anymore

**Comment by bruberu** [comment]
Should be fixed now that 1.10.2 has been out a while.
