### ISSUE TITLE
server startup chash

### ISSUE THREAD

**Issue by SinusoidalC** [bruberu/GregTechFoodOption#63]
[crash-2023-12-08_00.15.40-server.txt](https://github.com/bruberu/GregTechFoodOption/files/13623104/crash-2023-12-08_00.15.40-server.txt)
CrasCrash when server startup
GTFO Version 1.10.2，GTCEu Version 2.8.2-beta

**Comment by bruberu** [comment]
https://cdn.discordapp.com/attachments/852616265650012241/1181574979083587654/gregtechfoodoption-1.10.2.jar?ex=65818e73&is=656f1973&hm=0079f4e139b9b53378c5a4b8cd0ecb54c8c733fe7562f02eea174656a22756bb&
This beta version should work fine.

**Comment by SinusoidalC** [comment]
wow ，thanks

**Comment by SinusoidalC** [comment]
problem solved ，appreciate
