### ISSUE TITLE
Muffler Hatch  does not have an auto exit

### ISSUE THREAD

**Issue by Redangys** [bruberu/GregTechFoodOption#66]
![Screenshot_1](https://github.com/bruberu/GregTechFoodOption/assets/158020860/e0aca4cf-efd3-46af-a30b-f566f5c451a9)
It clogs up in 4 minutes and the big bronze boiler stops working, hence no steam is produced, turbines stand up. Can you add the possibility of at least using funnels and slides to get ash out of it?

**Comment by bruberu** [comment]
This mod does not intend to modify GTCEu large boilers. Also, this appears to be on a modern version (considering the colored LV), so I would be unable to do anything about this in GTFO from 1.12 anyways.
