### ISSUE TITLE
Greenhouse recipe doesn't show in JEI

### ISSUE THREAD

**Issue by BlazeHunterVN1610** [bruberu/GregTechFoodOption#69]
Modpack: Nomifactory 1.7-alpha-3
GTFO version: 1.11.1

Seeing the usage of the greenhouse in JEI only shows the multiblock preview, but not the recipe for sapling and wood
![2024-03-26_22 42 06](https://github.com/bruberu/GregTechFoodOption/assets/111768452/321902c1-f7d0-49ae-99de-81aeba546a3b)

The greenhouse still works if you have right input and correct circuit configuration
![2024-03-26_22 42 09](https://github.com/bruberu/GregTechFoodOption/assets/111768452/5d84e816-2df8-469b-ab02-f1251ffd0695)
![2024-03-26_22 42 10](https://github.com/bruberu/GregTechFoodOption/assets/111768452/d7059830-9b49-4aa6-b2a8-726b786afca3)

Also, I don't know why the greenhouse produces leaves instead of sapling (is this intended?)
![2024-03-26_22 42 14](https://github.com/bruberu/GregTechFoodOption/assets/111768452/4f5ef887-4d82-43b3-8595-fc33a2e04b36)

**Comment by bruberu** [comment]
I will investigate; can you look at the recipes for other machines?

As for your second question, yes, GTFO recipes naturally give back far more leaves than saplings, and there is a recipe (on circuit 3, I think) that's best suited for creating saplings for use in other greenhouses (or just getting a minor amount of wood).

**Comment by BlazeHunterVN1610** [comment]
Other GT multiblock still show me the recipe normally. I also look at the kitchen multilblock usage recipe, but I don't really know if it actually has recipe to show

**Comment by bruberu** [comment]
The kitchen does not have normal recipes, correct. It appears your issue is something specific to Nomifactory CEu, so I'm going to attempt to install it now. You could also send me your log file as well.

**Comment by bruberu** [comment]
Alright, I've identified the issue as coming from Nomi Labs.

**Comment by BlazeHunterVN1610** [comment]
I remember IntegerLimit said something about a new grennhouse in nomi. When i search JEI, i thought they didn't include it in the alpha release. Maybe it is hidden in the JEI?

**Comment by bruberu** [comment]
Well, they at least added the recipe category for the Nomi Labs greenhouse, and it happens to have the exact same ID as that of GTFO's. I'm currently working out this issue with him :)
